### ISSUE TITLE
Make error (OSX: El Capitan)

### ISSUE THREAD

**Issue by pasknel** [miek/inspectrum#123]
I am having the following errors during make (using OSX El Capitan) :

Undefined symbols for architecture x86_64:
  "_freqdem_create", referenced from:
      FrequencyDemod::work(void*, void*, int, long long) in frequencydemod.cpp.o
  "_freqdem_demodulate", referenced from:
      FrequencyDemod::work(void*, void*, int, long long) in frequencydemod.cpp.o
  "_freqdem_destroy", referenced from:
      FrequencyDemod::work(void*, void*, int, long long) in frequencydemod.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by miek** [comment]
That sounds like it could be caused by using an old version of liquid-dsp
