### ISSUE TITLE
Debian Build Error: Cmakelists.txt

### ISSUE THREAD

**Issue by ae7lt** [miek/inspectrum#126]
My efforts to install Inspectrum to Ubuntu are resulting in the following error when I execute the cmake .. command: Cmake Error: Source directory "/home/username" does not appear to contain CMakelists.txt.

Here is what I have done:
git clone git://github.com/jgaeddert/liquid-dsp.git
cd liquid-dsp
./bootstrap.sh
./configure
make
sudo make install
cd ..
sudo apt-get install qt5-default libfftw3-dev cmake pkg-config
mkdir build
cd build
cmake ..

I've verified that the CMakelists.txt file is not in the /home/username/build directory.

Why isn't this CMakelists.txt file being made?  If its relevant, I installed GNU Radio using Pybombs to a prefix/default directory.

**Comment by miek** [comment]
The list of commands you posted is missing the cloning of the inspectrum source itself, so make sure you do that :)
If you do have it and it was just a typo, make sure you're in the `inspectrum` directory when you `mkdir build; cd build; etc..`

**Comment by ae7lt** [comment]
Thanks for taking the time to respond.  Issue resolved, but with questions.   I did neglect to clone inspectrum first.  My thinking was that I needed to successfully install the dependencies first (Liquid-dsp, qt5-default,, libfftw3-dev, cmake, pkg-config).  Should I have cloned inspectrum first and then installed dependencies?  I discovered that Inspectrum is already included within Ubuntu as a package so I used "sudo apt-get install inspectrum" and it ran successfully without mkdir build, cd build etc. Although I 'm confused as to where it was installed.  I can't find any directory or file that looks like it would be related to inspectrum. I run it from my home directory, so should I expect to find the Inspectrum related program files in my home directory or maybe root usr directory?  Also, am I correct in my thinking that I did not need to "build/compile" using apt-get because the Inspectrum package included in Ubuntu was already compiled whereas the cloning from github would be all source files that require "build or compiling?"  Obviously, I'm new to to Linux.  Hopefully I can learn from my many missteps.  Thanks for the help.

**Comment by miek** [comment]
It doesn't matter whether you clone the code before or after installing dependencies.
Using the packaged Ubuntu version would mean that you don't need to mess around with building/installing dependencies, but that version is quite old now so it can be worth the effort to build the newest version.
