### ISSUE TITLE
don't make from MACOS

### ISSUE THREAD

**Issue by wizz777** [miek/inspectrum#133]
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:47:5: error: function-like macro 'QT_HAS_INCLUDE' is not
      defined
#if QT_HAS_INCLUDE(<chrono>)
    ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:77:25: error: expected ';' at end of declaration list
    inline void unlock() Q_DECL_NOTHROW {
                        ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:91:29: error: expected ';' at end of declaration list
    bool isRecursive() const Q_DECL_NOTHROW;
                            ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:94:30: error: expected ';' at end of declaration list
    inline bool fastTryLock() Q_DECL_NOTHROW {
                             ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:109:26: error: expected ';' at end of declaration list
    void unlockInternal() Q_DECL_NOTHROW;
                         ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:73:26: error: too few arguments to function call, single
      argument 'timeout' was not specified
            lockInternal();
            ~~~~~~~~~~~~ ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:108:5: note: 'lockInternal' declared here
    bool lockInternal(int timeout) QT_MUTEX_LOCK_NOEXCEPT;
    ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:131:18: error: expected ';' at end of declaration list
    void unlock() Q_DECL_NOTHROW;
                 ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:136:5: error: function-like macro 'QT_HAS_INCLUDE' is not
      defined
#if QT_HAS_INCLUDE(<chrono>)
    ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:155:29: error: expected ';' at end of declaration list
    bool isRecursive() const Q_DECL_NOTHROW
                            ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:163:5: error: function-like macro 'QT_HAS_INCLUDE' is not
      defined
#if QT_HAS_INCLUDE(<chrono>)
    ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:209:25: error: expected ';' at end of declaration list
    inline void unlock() Q_DECL_NOTHROW
                        ^
/Users/wizz/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmutex.h:198:13: error: use of undeclared identifier 'Q_LIKELY'
        if (Q_LIKELY(m)) {
            ^
12 errors generated.
make[2]: *** [CMakeFiles/inspectrum.dir/amplitudedemod.cpp.o] Error 1
make[1]: *** [CMakeFiles/inspectrum.dir/all] Error 2
make: *** [all] Error 2

**Comment by miek** [comment]
Are you still having trouble building on macOS?

As far as I can see, all of those errors relate to some problem within your Qt install.

I'll close this for now since it's quite old and probably not something I can fix in inspectrum, but feel free to reopen if you're still having issues.
