### ISSUE TITLE
abort()s for unrecognised file on command line

### ISSUE THREAD

**Issue by FauxFaux** [miek/inspectrum#134]
If you run inspectrum with an invalid argument, it crashes:

```
$ inspectrum file-does-not-exist.foo
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error opening file: No such file or directory (2)
zsh: abort (core dumped)  inspectrum no-such-file.foo

$ echo $?
134
```

Would be cool if this gave a more normal error exit code for this case.

**Comment by miek** [comment]
This was fixed in 04b989142f790aa8e0347a149627c6716d5928cc - the exception is now caught and a message box error is displayed.
