### ISSUE TITLE
Export samples with Decimation=0 creates endless file

### ISSUE THREAD

**Issue by henrythasler** [miek/inspectrum#140]
**Expected behavior:**
While exporting samples with the context menu, inspectrum allows to choose the decimation. Although a decimation of "0" does not make sense, the program must be robust in this situation or prevent entering "0" altogether. It is expected that the output file is not larger than 1MB (small range selected).

**Observed behavior:**
After pressing "save", inspectrum starts writing the file but never stops. Writing more and more data and the UI becoming unresponsive. A forced quit/kill stops the program leaving several GB of data in the file. The file content was not examined further. It was also not determined if there is some limit to the written filesize.

![screenshot from 2018-01-05 16-55-06](https://user-images.githubusercontent.com/6277203/34617008-48fbb0c2-f23a-11e7-9b06-df222b005eaa.png)

**Version info**
inpectrum cloned and build on 2018-01-04 from master-branch.

Ubuntu 17.10 with X-Org
```
$ uname -s -r -v -p -i -o
Linux 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 GNU/Linux
```

**Comment by miek** [comment]
Thanks!

**Comment by schneider42** [comment]
Oops :)
