### ISSUE TITLE
QTWidgets

### ISSUE THREAD

**Issue by eudomoniacc** [miek/inspectrum#141]
By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

i am getting this error while building in Kali 2018.1

**Comment by miek** [comment]
You probably need to install Qt5Widgets. It's under the package `libqt5widgets5` on Debian, I don't know about Kali
