### ISSUE TITLE
How to run??

### ISSUE THREAD

**Issue by RCCRAFT1** [miek/inspectrum#153]
How do i run the program/file on my computer??

**Comment by sterlingrpi** [comment]
What OS are you using? I have Linux and I installed it with:

sudo apt-get update
sudo apt-get install inspectrum

And to run it I just typed:

inspectrum

**Comment by RCCRAFT1** [comment]
I’m using windows

**Comment by sterlingrpi** [comment]
hmm. I don't think there is an official windows build. Maybe try a VM or another software tool like inspectrum

https://github.com/miek/inspectrum/wiki/Build

**Comment by RCCRAFT1** [comment]
Ok
