### ISSUE TITLE
no horizontal slider after startup

### ISSUE THREAD

**Issue by geo207** [miek/inspectrum#173]
Hello,

I downloaded inspectrum a few days ago, but there is no horizontal zoom slider on the signal area (see first screenshot). I tried resizing and adjusting the window as suggested in issue #170, but it had no effect.  Also, when I right click and then click on one of the four options, a new area opens at the bottom of the window, and if I do that again then another new area opens at the bottom; this time the second area is a bright green, but with other signal files it is a different color (see second screenshot).  I don't think these new areas are supposed to appear based on what I've read about inspectrum online.  I am using a Raspberry Pi 4 (8 GB) and the version of inspectrum is 0.2-1.  In the terminal window, when I start inspectrum there are always 6 lines that read, "libpng warning: iCCP: known incorrect sRGB profile"   I don't know if this is connected to the horizontal zoom slider missing.  Can anyone tell me why I am not getting the slider and what the remedy might be?  I don't understand the coding solution in #170 and I'm not sure it pertains to my problem in any case.  I'm very disappointed as I have signal files ready to roll!  Thanks and here are two screenshots:  

![2020-10-03-090150_1920x1080_scrot](https://user-images.githubusercontent.com/66704892/94992829-916d7f80-055a-11eb-9930-dff606229324.png)

![2020-10-03-090237_1920x1080_scrot](https://user-images.githubusercontent.com/66704892/94992835-992d2400-055a-11eb-9f76-9989cc9ccd1f.png)

**Comment by geo207** [comment]
twelve hours later....I think I figured it out now.  Still working out how to count symbols, but I think I found the cursor and the zoom. 

 
![2020-10-03-210043_1920x1080_scrot](https://user-images.githubusercontent.com/66704892/95004693-a2e77380-05bc-11eb-9194-afb87847dbc8.png)

**Comment by miek** [comment]
> Still working out how to count symbols

You can drag the cursors so that a transition in the signal always lands on a dotted line, and that will setup the symbol rate roughly. Then you can increase the symbol count and the cursors will expand out to cover more of the signal & count out the symbols (you may need to continue tweaking the rate as you go)
