### ISSUE TITLE
Submodule libsigmf?

### ISSUE THREAD

**Issue by miek** [miek/inspectrum#181]
It might be a good idea to submodule libsigmf rather than making users (& package maintainers) install it for SigMF support

**Comment by schneider42** [comment]
@Sec42 recently had quite a hard time installing libsigmf into his (pybombs) installation. I think he might have some input here.

**Comment by Sec42** [comment]
I'm not sure if it's really applicable to this question of using a submoduleor not.

I had trouble building it in a pybombs environment. To get it to build cleanly I had to use specific (old) versions of flatbuffers & nlohmann_json.

source: git+https://github.com/google/flatbuffers
gitrev: 71aca81ff9

and

source: git+https://github.com/nlohmann/json.git
gitbranch: v3.7.1
