### ISSUE TITLE
Zero pad to compensate for nonzero FFT length

### ISSUE THREAD

**Issue by jacobagilbert** [miek/inspectrum#219]
Instantaneous energy and the spectrogram tiles do not line up correctly in Inspectrum. This is most obvious when using larger FFT lengths and the amplitude plot, but also very noticeable with SigMF Annotations, for example, in the screenshot below shows the spectrogram tile showing energy well before the annotation and actual time domain energy begins:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/7121282/203126769-53470775-3233-48d7-8928-4571fc43786b.png">

At larger FFT sizes this misalignment becomes more obvious as the temporal ambiguity (same number of samples as FFT length) increases.

To resolve this, the data should be zero padded with length `NFFT/2` in which case the spectrogram will be nicely aligned (with expected temporal smearing still of course):

<img width="910" alt="image" src="https://user-images.githubusercontent.com/7121282/203126104-baaaeec8-6463-420a-b234-d58ff677d7af.png">

**Comment by daniestevez** [comment]
Just seen this issue. I've also realized this problem, and sent a PR that solves the problem in a slightly different way (#227).

**Comment by miek** [comment]
Fixed in #227
