### ISSUE TITLE
Inspectrum crashes in viewing small files

### ISSUE THREAD

**Issue by chr1s-uni** [miek/inspectrum#223]
When I load a small file like 8 kb into inspectrum and increase the size of the window inspectrum crashes consistently

**Comment by jdemel** [comment]
I ran a quick test. Generated a small file with

```python
testsize = 1024
test = np.random.normal(0.0, 1.0, testsize) + 1.j * np.random.normal(0.0, 1.0, testsize)
test = test.astype(np.complex64)
test.tofile("testdata.fc32"))
```

opened the file in inspectrum with the waterfall plot only. Zoom, window resizing etc. works.

As soon as I add a derived plot, it crashes.
`floating point exception (core dumped)  [PATH_TO_INSPECTRUM]/inspectrum testdata.fc32`
