### ISSUE TITLE
Please tag your latest release of Inspectrum

### ISSUE THREAD

**Issue by loidmen** [miek/inspectrum#226]
The last tagged release of Inspectrum does not have SigMF support enabled.

I'm using inspectrum on a windows machine using the conda installation by Ryan Volz , radioconda (gnuradio for windows) and conda installs tagged releases. If you tag the latest release of Inspectrum which has SigMF support, this will allow windows users that added feature of Inspectrum too.

Thank you for your support and thank you for making such a helpful tool available for all.

**Comment by miek** [comment]
Done!

**Comment by loidmen** [comment]
Thank you all very much.
