### ISSUE TITLE
missing dep on pkgconfig

### ISSUE THREAD

**Issue by ZeroChaos-** [miek/inspectrum#24]
-- Found PkgConfig: /usr/bin/x86_64-pc-linux-gnu-pkg-config (found version "0.28") 

something is looking for pkgconfig but you don't list it as a build time dep.

**Comment by dominicgs** [comment]
pkg-config is required, cmake requires it to find fftw3 (and possibly QT5).

**Comment by dominicgs** [comment]
Fixed in #26
