### ISSUE TITLE
tuner.cpp std::abs error

### ISSUE THREAD

**Issue by devnulling** [miek/inspectrum#54]
When building the waveform branch on OSX, I ran into this error below. Adding "#include < cstdlib >" without the spaces to tuner.cpp resolved this error.

[ 90%] Building CXX object CMakeFiles/inspectrum.dir/tuner.cpp.o
/Users/user/sdr/inspectrum-waveform/tuner.cpp:45:34: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
        _deviation = std::max(2, std::abs(sender->pos() - cfCursor->pos()));
                                 ^~~~~~~~
                                 abs
/usr/include/stdlib.h:129:6: note: 'abs' declared here
int      abs(int) __pure2;
         ^
1 error generated.
make[2]: *** [CMakeFiles/inspectrum.dir/tuner.cpp.o] Error 1
make[1]: *** [CMakeFiles/inspectrum.dir/all] Error 2
make: *** [all] Error 2

**Comment by miek** [comment]
Fixed, thanks
