### ISSUE TITLE
Feature request for adding notes

### ISSUE THREAD

**Issue by vsboost** [miek/inspectrum#62]
Hi Miek,

Sorry one more feature request if possible, i would love to have the ability to add some notes to a file, in particular the 1's and 0's lined up with the cursors and the ability to copy and paste them to the clipboard, something like what i have attached.  Thanks again.
<img width="405" alt="screenshot from 2016-04-20 08-48-45" src="https://cloud.githubusercontent.com/assets/11001973/14658245/af0ce298-06d5-11e6-8fae-f0e3854ff3fd.png">

**Comment by miek** [comment]
So there's a plan for something like this that I'm working towards in the waveform branch, but it's not going to be notes that you can save/load/copy.

The idea is to display extra plots with simple demod functions (frequency, amplitude, etc.) then use the timing info. from the cursors to extract symbols automatically from the thresholded plot (bottom one in pic):
![inspectrum-notes](https://cloud.githubusercontent.com/assets/578095/14658660/8e625c78-068d-11e6-87a2-38e218107cf0.jpg)

I've made #63 to keep track of that so I'll close this. Cheers!

**Comment by vsboost** [comment]
That seems an even better idea, thanks again.

On 20 Apr 2016, at 9:27 AM, Mike Walters <notifications@github.com<mailto:notifications@github.com>> wrote:

So there's a plan for something like this that I'm working towards in the waveform branch, but it's not going to be notes that you can save/load/copy.

The idea is to display extra plots with simple demod functions (frequency, amplitude, etc.) then use the timing info. from the cursors to extract symbols automatically from the thresholded plot (bottom one in pic):
[inspectrum-notes]<https://cloud.githubusercontent.com/assets/578095/14658660/8e625c78-068d-11e6-87a2-38e218107cf0.jpg>

I've made #63<https://github.com/miek/inspectrum/issues/63> to keep track of that so I'll close this. Cheers!
