### ISSUE TITLE
Scroll bar indicator colour

### ISSUE THREAD

**Issue by vsboost** [miek/inspectrum#64]
One more i promise. :-)

Is it possible to make the scroll bar indicator a darker or different colour i find it hard to see it at times.

<img width="960" alt="screenshot from 2016-04-20 10-31-18" src="https://cloud.githubusercontent.com/assets/11001973/14659918/7a5eb482-06e3-11e6-9f5a-93397175bc11.png">

**Comment by miek** [comment]
I'm not sure on that one. I can modify it, but it seems like something that should be done in the system theme.
Do other Qt applications have the same issue for you?

**Comment by vsboost** [comment]
You might be right there, I didn't know it was configured elsewhere, I'll see if I can work it out.

Cheers
