### ISSUE TITLE
building waveform

### ISSUE THREAD

**Issue by vsboost** [miek/inspectrum#66]
![screenshot from 2016-04-24 09-41-39](https://cloud.githubusercontent.com/assets/11001973/14764594/d44867ac-0a00-11e6-92a7-6449ae6a7e48.png)
Hi miek,

Im not sure what i have done here but i just tried to build the latest waveform commits and my inspectrum looks like the master branch have lost the horizontal selection bars.  I wanted to see the plotview: Basic symbol extraction work you just made.
 
even started from scratch

git clone https://github.com/miek/inspectrum.git
git checkout waveform
mkdir build
cmake ..
make
./inspectrum

Any suggestions

**Comment by miek** [comment]
The tuner overlay only shows up when there's a derived plot using it (so it doesn't get in the way if you only want to look at the spectrogram).
You can right click on the spectrogram to add a plot.

This feature won't be that useful for the signal you're looking at, since there's no amplitude plot yet.

**Comment by vsboost** [comment]
Ahh thanks miek,

**Comment by miek** [comment]
Added an amplitude plot and scaling, enjoy :)

![inspectrum-amplitude](https://cloud.githubusercontent.com/assets/578095/14764818/cb5551f2-09bd-11e6-8e62-9b12bf3838f0.jpg)

Note: the threshold plot won't work well on this (need to think about it some more), but you can paste into python or whatever to threshold it easily.

**Comment by vsboost** [comment]
Thanks miek,
Looking good :-)
![screenshot from 2016-04-24 11-04-53](https://cloud.githubusercontent.com/assets/11001973/14764887/7562ac00-0a0c-11e6-9d3f-66e1157c483b.png)

**Comment by vsboost** [comment]
Loving this, and thanks for the python script to convert to 1's & 0's.  Ill just add it to this comment for reference.

syms = [1.99554, 0.00911547, 2.04077, 0.0130324, 2.02553, 0.0156159, 2.00305, 0.00284353, 1.92315, 0.0208421, 1.9628, 0.00791253, 1.96002, 0.0145462, 1.93397, 0.0201539, 1.95594, 0.0139064, 1.93589]
print map(lambda x: 1 if x > 1 else 0, syms)
