### ISSUE TITLE
No horizontal line (cursor?) on Ubuntu 15 / 32 Bit

### ISSUE THREAD

**Issue by DE8MSH** [miek/inspectrum#74]
Hi.

For me there's no horizontal line for analyzing signal...

http://www.bilder-upload.eu/show.php?file=5f5fc5-1465486010.jpg

What's wrong? Am I unsing the tool the wrong way?

**Comment by miek** [comment]
If you mean the tuner overlay like in ![inspectrum-notes](https://cloud.githubusercontent.com/assets/578095/14658660/8e625c78-068d-11e6-87a2-38e218107cf0.jpg) then just right click the spectrogram, add an amplitude/frequency plot and it'll show up.
