### ISSUE TITLE
max FFT size breaks view

### ISSUE THREAD

**Issue by mike01** [miek/inspectrum#83]
Setting the FFT size to max breaks the view (does not restore). Version: Master branch on 1.9.2016
[hackrf_sendtest.cu8.tar.zip](https://github.com/miek/inspectrum/files/450602/hackrf_sendtest.cu8.tar.zip)

![screenshot-20160901-221346](https://cloud.githubusercontent.com/assets/3173708/18182615/06d9bd46-7091-11e6-84cc-5f5871315332.png)

**Comment by miek** [comment]
Same issue as #89
