### ISSUE TITLE
Short files are rendered with a red block next to them and cause UI glitches

### ISSUE THREAD

**Issue by schneider42** [miek/inspectrum#89]
When opening a short file a huge red block gets displayed left to it.

Playing with the controls can introduce further UI glitches:

![screenshot from 2016-09-15 08 53 49](https://cloud.githubusercontent.com/assets/452051/18540936/4e4fa60e-7b22-11e6-91cd-ccdc5870b933.png)

**Comment by miek** [comment]
e054965 fixes some of this (it doesn't try to plot negative parts anymore), but there's now some corruption at the top end of the plot since spectrogramplot doesn't respect `viewRange.maximum`
