### ISSUE TITLE
Inspectrum requires file to open

### ISSUE THREAD

**Issue by erichahn** [miek/inspectrum#90]
I tried to open inspectrum after a fresh install and it immediately opens a window that grabs the screen behind this new window that opens. Next the window freezes, grays out, and never opens.

I next tried opening inspectrum and also gave it a file to look at and it finally worked!

I don't think inspectrum should REQUIRE a file to open properly. I believe this is a bug, unless it is a design choice (that I don't agree with, but I'm only just starting to use it).

Any thoughts?

I should mention that I am on Ubuntu 16.04, gnuradio 3.7

![inspectrum grabs screen and freezes](https://cloud.githubusercontent.com/assets/5660505/18574244/87c61e7a-7b88-11e6-89f4-8368c837c808.png)

**Comment by miek** [comment]
That's a bug, looks like I broke it in the last few commits and caused an inf. loop in `PlotView::paintTimeScale`. I'll get it fixed soon, cheers for the report!

**Comment by schneider42** [comment]
I guess `durationPerTick` becomes zero and the loops never finish. Both loops should get a check if the used step is > 0.

**Comment by miek** [comment]
Fixed in d747e9daffbde3e45df56bb2804e2d93fa6eaa54
