### ISSUE TITLE
Red UI issue

### ISSUE THREAD

**Issue by tikf124** [miek/inspectrum#92]
Hi

I opened the file, red screen is generated.+

What is the problem?

I had to collect the files using the following command:

hackrf_transfer -r test.raw -f 27000000 -s 8000000 

file down  : https://www.dropbox.com/s/87v6as27j9mc62h/up.raw?dl=0

Thanks

**Comment by miek** [comment]
It's interpreting the file as the wrong type. You should put a `.cs8` extension on HackRF recordings for inspectrum to pick up the right type. More here: https://github.com/miek/inspectrum#input

**Comment by tikf124** [comment]
Thank you for your help.

I solved the problem.
